### ISSUE TITLE
Allow to deploy multiple replicas of ApiServer

### ISSUE THREAD

**Issue by Wihrt** [DependencyTrack/helm-charts#65]
Hello !

In the current state of the Helm Chart, we cannot deploy more than 1 instance of the API-Server.
https://github.com/DependencyTrack/helm-charts/blob/main/charts/dependency-track/templates/api-server/statefulset.yaml#L10

- Does the API Server supports multiple instances ?
If yes, it would be great to allow to change the replicaCount on the API Server component :)

I'll make a PR, if I can find some time :)

**Comment by nscuro** [comment]
It is [not possible](https://github.com/DependencyTrack/dependency-track/issues/903) to deploy more than one instance, the hard-coded `replicas` value is intentional.

The good news is: Where working on this in the context of project [hyades](https://github.com/DependencyTrack/hyades), which will eventually become Dependency-Track v5.x. Among a lot of other goodies, it *does* support multiple API server instances.
